## The workflow canonical/observability/.github/workflows/rock-release-dev.yaml@main
## does not allow setting a GHCR repo where to publish at the moment.
## We thus copy it below and adapt it.

# name: "Publish ROCK to GHCR:dev"

# concurrency:
#   group: ${{ github.workflow }}-${{ github.ref }}
#   cancel-in-progress: true

# on:
#   workflow_dispatch: {}
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     uses: canonical/observability/.github/workflows/rock-release-dev.yaml@main
#     secrets: inherit
#     with:
#       rock-name: foxglove-studio

# Copied and adapted from
# https://github.com/canonical/observability/blob/34b7edb56094e8e3f01200ce49e01bf9dd6688ac/.github/workflows/rock-release-dev.yaml

name: Build ROCK and release dev tag to GHCR

on:
  workflow_call:
    # inputs:
      # rock-name:
        # description: "Name of the application for which to build the ROCK"
        # required: true
        # type: string
    secrets:
      OBSERVABILITY_NOCTUA_TOKEN:
        required: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Find the *latest* rockcraft.yaml
      id: find-latest
      run: |
        latest_rockcraft_file=$(find $GITHUB_WORKSPACE -name "rockcraft.yaml" | sort -V | tail -n1)
        rockcraft_dir=$(dirname ${latest_rockcraft_file#\./})
        echo "latest-dir=$rockcraft_dir" >> $GITHUB_OUTPUT

    - name: Setup LXD
      uses: canonical/setup-lxd@v0.1.1
      with:
        channel: latest/stable

    - name: Install dependencies
      run: |
        sudo snap install yq
        sudo snap install --classic rockcraft

    - name: Build ROCK
      run: |
        rockcraft_dir="${{ steps.find-latest.outputs.latest-dir }}"
        current_wd=$(pwd) && cd $rockcraft_dir
        rockcraft pack --verbose
        cd $current_wd
        cp $rockcraft_dir/foxglove-studio_*.rock $current_wd
        digest=$(skopeo inspect oci-archive:$(realpath ./foxglove-studio_*.rock) --format '{{.Digest}}')
        echo "digest=${digest#*:}" >> "$GITHUB_OUTPUT"

    - name: Upload ROCK to ghcr.io
      run: |
        sudo skopeo --insecure-policy copy oci-archive:$(realpath ./foxglove-studio_*.rock) docker://ghcr.io/canonical/foxglove-studio:dev --dest-creds "observability-noctua-bot:${{ secrets.OBSERVABILITY_NOCTUA_TOKEN }}"

    - name: Install Syft
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

    - name: Create SBOM
      run: syft $(realpath ./foxglove-studio_*.rock) -o spdx-json=foxglove-studio.sbom.json

    - name: Upload SBOM
      uses: actions/upload-artifact@v3
      with:
        name: foxglove-studio-sbom
        path: "foxglove-studio.sbom.json"
    - name: Upload locally built ROCK artifact
      uses: actions/upload-artifact@v3
      with:
        name: foxglove-studio-rock
        path: "foxglove-studio_*.rock"